name: OrthancDicomwebS3Plugin

on:
  workflow_dispatch:

env:
  # Instruction to use environment variable https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
  BUILD_TYPE: Release
  MAJOR_NUMBER: 0

jobs:
  build_orthanc_image:
    runs-on: ubuntu-latest

    steps:
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}

    - name: prepare os packages
      run: |
        echo "VERSION_NUMBER=$MAJOR_NUMBER.$BUILD_NUMBER" >> $GITHUB_ENV
        echo -n "Build number is $BUILD_NUMBER." && echo "Version is $VERSION_NUMBER"
        sudo apt-get update

    - name: download dockerfile
      working-directory: '/home/runner'
      run: |
        git init orthweb && cd orthweb
        git remote add origin https://github.com/hmesha/orthweb.git && git config core.sparsecheckout true
        echo 'builder/*' >> .git/info/sparse-checkout && git pull --depth=1 origin main
        docker --version

    - name: run multi-stage build
      working-directory: '/home/runner/orthweb/builder'
      run: |
        docker build -t "hmesha/orthanc:${{ env.VERSION_NUMBER }}" .
        docker image ls

    - name: Login to DockerHub # no need to specify registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        logout: true

    - name: build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: '/home/runner/orthweb/builder'
        #platforms: linux/amd64
        push: true
        tags: |
          hmesha/orthanc:latest
          hmesha/orthanc:${{ env.VERSION_NUMBER }}

    - name: image digest
      run: echo Image ${{ steps.docker_build.outputs.digest }} was published to DockerHub as hmesha/orthanc:${{ env.VERSION_NUMBER }}
